### ISSUE TITLE
Jni-headers-maven-plugin:1.0.2 can't find JDK_HOME on Windows 8

### ISSUE THREAD

**Issue by David-Noble-at-work** [alexkasko/jni-headers-maven-plugin#1]
OS: Windows 8
Shell: Cygwin

JAVA_HOME is set correctly for Maven 3. Because the plugin reports an error, I set JDK_HOME="$JDK_HOME". The plugin still reports an error: 

[ERROR] Failed to execute goal com.alexkasko.maven:jni-headers-maven-plugin:1.0.2:javah (javah) on project voicebox-updatepersonaldata-application: Cannot find JDK home directory, check JDK_HOME property -> [Help 1]

---
## Stack Trace

org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.alexkasko.maven:jni-headers-maven-plugin:1.0.2:javah (javah) on project voicebox-updatepersonaldata-application: Cannot find JDK home directory, check JDK_HOME property^M
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)^M
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)^M
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)^M
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)^M
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)^M
    at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)^M
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)^M
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)^M
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)^M
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)^M
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)^M
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)^M
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)^M
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)^M
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)^M
    at java.lang.reflect.Method.invoke(Method.java:601)^M
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)^M
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)^M
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)^M
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)^M
Caused by: org.apache.maven.plugin.MojoFailureException: Cannot find JDK home directory, check JDK_HOME property^M
    at com.alexkasko.maven.jniheaders.JavahMojo.execute(JavahMojo.java:116)^M
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)^M
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)^M
    ... 19 more^M
Caused by: java.io.IOException: Cannot find JDK home directory, check JDK_HOME property^M
    at com.alexkasko.maven.jniheaders.Utils.jdkHome(Utils.java:40)^M
    at com.alexkasko.maven.jniheaders.JavahMojo.execute(JavahMojo.java:91)^M
    ... 21 more^M

**Comment by alexkasko** [comment]
There was a java home validation typo, `1.0.3` should be in maven central in few hours, please reopen if that won't help.

**Comment by David-Noble-at-work** [comment]
Same issue with the 1.0.3 build on Windows 8:

 [ERROR] Failed to execute goal com.alexkasko.maven:jni-headers-maven-plugin:1.0.3:javah (javah) on project voicebox-updatepersonaldata-application: Cannot find JDK home directory, check JDK_HOME property -> [Help 1]
C:\Program Files\Cygwin\bin\bash: syntax error near unexpected token `('
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: org.apache.maven.plugin.MojoFailureException: Cannot find JDK home directory, check JDK_HOME property
        at com.alexkasko.maven.jniheaders.JavahMojo.execute(JavahMojo.java:116)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
        ... 19 more
Caused by: java.io.IOException: Cannot find JDK home directory, check JDK_HOME property
        at com.alexkasko.maven.jniheaders.Utils.jdkHome(Utils.java:40)
        at com.alexkasko.maven.jniheaders.JavahMojo.execute(JavahMojo.java:91)
        ... 21 more

**Comment by alexkasko** [comment]
Interesting, I'll check this in cygwin.

**Comment by David-Noble-at-work** [comment]
Thanks. Here are the settings of my JAVA_HOME and JDK_HOME variables:

JAVA_HOME='C:/PROGRA~1/Java/jdk1.7.0_21'
JDK_HOME='C:/PROGRA~1/Java/jdk1.7.0_21'

They're set to the same value.

**Comment by David-Noble-at-work** [comment]
The same message appears with 1.0.3 sorry to say. I'll reopen the issue:

 [ERROR] Failed to execute goal com.alexkasko.maven:jni-headers-maven-plugin:1.0.3:javah (javah) on project voicebox-updatepersonaldata-application: Cannot find JDK home directory, check JDK_HOME property -> [Help 1]

C:\Program Files\Cygwin\bin\bash: syntax error near unexpected token `('

```
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)

    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)

    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)

    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
```

Caused by: org.apache.maven.plugin.MojoFailureException: Cannot find JDK home directory, check JDK_HOME property

```
    at com.alexkasko.maven.jniheaders.JavahMojo.execute(JavahMojo.java:116)

    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)

    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)

    ... 19 more
```

Caused by: java.io.IOException: Cannot find JDK home directory, check JDK_HOME property

```
    at com.alexkasko.maven.jniheaders.Utils.jdkHome(Utils.java:40)

    at com.alexkasko.maven.jniheaders.JavahMojo.execute(JavahMojo.java:91)

    ... 21 more
```

**Comment by alexkasko** [comment]
It was quite a silly bug, I forgot that `javap` and `javah` are called `javap.exe` and `javah.exe` on windows.

I had no luck with (quickly) making maven running in cygwin (maybe my customized cygwin version is to blame). 
I've created test project - `https://bitbucket.org/alexkasko/jni-headers-example.git` and version 1.0.5 of plugin with fix for windows and more logging. Could you please try this project in your cygwin environment?

Successful run should be like this:

```
# touch files to ensure rewrite
$ touch src/main/java/com/alexkasko/maven/example/NativeFunctionsAccessor.java
$ touch src/main/java/com/alexkasko/maven/example/JavaMethodsInterface.java
$ mvn compile
[INFO] Scanning for projects...
... 
[INFO] --- jni-headers-maven-plugin:1.0.5:javah (javah) @ jni-headers-example ---
[INFO] [/home/alex/java/openjdk6_b27/bin/javah, -o, /home/alex/projects/bitbucket/jni-headers-example/src/main/jni/jni_functions.h, com.alexkasko.maven.example.NativeFunctionsAccessor]
[INFO] 
[INFO] --- jni-headers-maven-plugin:1.0.5:javap (javap) @ jni-headers-example ---
[INFO] [/home/alex/java/openjdk6_b27/bin/javap, -s, com.alexkasko.maven.example.JavaMethodsInterface]
```

Environment variables logging is added as `DEBUG` level messages and could be seen running maven like this:

```
$ mvn compile -X
# lots of output
...
[INFO] --- jni-headers-maven-plugin:1.0.5:javah (javah) @ jni-headers-example ---
...
[DEBUG] Configuring mojo com.alexkasko.maven:jni-headers-maven-plugin:1.0.5:javah from plugin realm ClassRealm[plugin>com.alexkasko.maven:jni-headers-maven-plugin:1.0.5, parent: sun.misc.Launcher$AppClassLoader@16f0472]
[DEBUG] Configuring mojo 'com.alexkasko.maven:jni-headers-maven-plugin:1.0.5:javah' with basic configurator -->
...
# environment logging line
[DEBUG] getProperty("java.home"): [/home/alex/java/openjdk6_b27/jre]
[INFO] [/home/alex/java/openjdk6_b27/bin/javah, -o, /home/alex/projects/bitbucket/jni-headers-example/src/main/jni/jni_functions.h, com.alexkasko.maven.example.NativeFunctionsAccessor]
```

Plugin first tries to find `javap` and `javah` relative to `java.home` java property. Then it search relative to `JAVA_HOME` environment variable, then relative to `JDK_HOME`.

Please reopen if it won't help.

**Comment by David-Noble-at-work** [comment]
Here's the error I'm getting with 1.0.5

[ERROR] Failed to execute goal com.alexkasko.maven:jni-headers-maven-plugin:1.0.5:javah (javah) on project voicebox-updatepersonaldata-application: Cannot find javah path, check 'javahPath' property -> [Help 1]

JDK_HOME and JAVA_HOME are correctly defined. ${JDK_HOME}/bin is on my path. I tried defining javahPath on the maven command line as -DjavahPath='C:\Program Files\Java\jdk1.7.0_21\bin\javah.exe' Should I be defining it differently?

Best,
David Noble

**Comment by alexkasko** [comment]
It's the same `.exe` issue with additional check before using `javah`, reopening, will look at it tonight.

**Comment by alexkasko** [comment]
Added another fix, still not tested on windows, hope it will work, version `1.0.6`

**Comment by David-Noble-at-work** [comment]
Progress:) Your plugin now runs on Windows 8 under cygwin. One question and one issue. First, here's my configuration:

```
  <plugin>
    <groupId>com.alexkasko.maven</groupId>
    <artifactId>jni-headers-maven-plugin</artifactId>
    <version>1.0.6</version>
    <executions>
      <execution>
        <!-- Generate header for com.seequest.Foo -->
        <id>com.voicebox.data.Database.Native</id>
        <phase>compile</phase>
        <goals>
          <goal>javah</goal>
        </goals>
        <configuration>
          <javahClass>com.seequest.Foo</javahClass>
          <javahOutputFilePath>${project.basedir}/src/main/c++/com.seequest.Foo.h</javahOutputFilePath>
        </configuration>
      </execution>
      <execution>
        <!-- Generate header for com.seequest.Bar -->
        <id>com.voicebox.NativeLoggingService</id>
        <phase>compile</phase>
        <goals>
          <goal>javah</goal>
        </goals>
        <configuration>
          <javahClass>com.seequest.Bar</javahClass>
          <javahOutputFilePath>${project.basedir}/src/main/c++/com.seequest.Bar.h</javahOutputFilePath>
        </configuration>
      </execution>
      <execution>
        <id>javap</id>
        <phase>compile</phase>
        <goals>
          <goal>javap</goal>
        </goals>
        <configuration>
          <javapClass>play.Logger</javapClass>
          <javapOutputFilePath>${project.basedir}/src/main/c++/play.Logger.h</javapOutputFilePath>
        </configuration>
      </execution>
    </executions>
  </plugin>
```

question: In my configuration I get one header, the first one. How do I generate headers for the native methods in more than one class?
issue: javap generates a header with no macros. I notice that you advertise that your plugin targets JDK 1.6, but I'm on JDK 1.7 and javap no longer supports the -h option. Is that the issue?

**Comment by alexkasko** [comment]
```
Progress:) Your plugin now runs on Windows 8 under cygwin. 
```

Thanks to you:) , I still haven't setup windows to test it.

```
One question and one issue.
```

This issue is becoming to long, I created two separate issues from your post, please comment there: 
- [Multiple execute clauses in plugin settings](https://github.com/alexkasko/jni-headers-maven-plugin/issues/2)
- [javap problems on Java 7](https://github.com/alexkasko/jni-headers-maven-plugin/issues/3)
